---
abstract: 'Extend your attribute interfaces'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  Any::Moose: 0.10
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MouseX-AttributeHelpers
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Mouse: 0.40
  Mouse::Meta::Attribute: 0
  Mouse::Util::TypeConstraints: 0
  perl: 5.6.2
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/masaki/mousex-attributehelpers.git
version: 0.07
